### PR TITLE
Webp assets

### PR DESCRIPTION
**Pull request by adrienpoly**
@marcoroth what do you think to serve webp assets rather than png ?
We can keep creating the original assets as png and convert them using that gem https://github.com/eagerworks/next_gen_images

```
rake next_gen_images:convert_app_images
```

### CODE REVIEW

**Comment by marcoroth** [comment]
Let me check, maybe Sketch can export them automatically for us too!

**Comment by adrienpoly** [comment]
well most of them are converted now but given the error in the CI it looks like this gem is not easy to install so probably a good idea to remove the gem from our dependencies

**Comment by marcoroth** [comment]
But also, I feels a bit redundant to have them both commited into the repo. Maybe there is a way so it can be done as part of `assets:precompile` rather then commiting the .webp versions.

**Comment by marcoroth** [comment]
Resolved via https://github.com/adrienpoly/rubyvideo/commit/e9bd44d565950a33d804a7e6a124266aee36d12e

**Pull request closed without merging**
